TITLE_1: PGF5295
TITLE_2: Teoria de Muitos Corpos e Matéria Condensada
SUBTITLE_1: Disciplina de pós-graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |

  <h3>Referências principais:</h3>
  <ul>
    <li>
      <strong>P. Coleman</strong>, <em>Introduction to Many-Body Physics</em>,
      Cambridge University Press (2015).
    </li>
    <li>
      <strong>S. Sachdev</strong>, <em>Quantum Phases of Matter</em>,
      Cambridge University Press (2023).
    </li>
    <li>
      <strong>A. L. Fetter</strong> e <strong>J. D. Walecka</strong>,
      <em>Quantum Theory of Many-Particle Systems</em>,
      Dover (2003) [ou McGraw-Hill (1971)].
    </li>
    <li>
      <strong>E. M. Lifshitz</strong> e <strong>L. P. Pitaevskii</strong>,
      <em>Statistical Physics, Part 2</em>,
      Butterworth-Heinemann (1980).
    </li>
    <li>
      <strong>X.-G. Wen</strong>, <em>Quantum Field Theory of Many-Body Systems</em>,
      Oxford University Press (2004).
    </li>
    <li>
      <strong>Henrik Bruus</strong> e <strong>Karsten Flensberg</strong>,
      <em>Many-Body Quantum Theory in Condensed Matter Physics</em>,
      Oxford University Press (2004).
    </li>
  </ul>

  <h3>Outras referências:</h3>
  <ul>
    <li>
      <strong>Abrikosov / Gorkov / Dzyaloshinskii</strong>,
      <em>Methods of Quantum Field Theory in Statistical Physics</em>.
    </li>
    <li>
      <strong>Altland</strong> e <strong>Simons</strong>,
      <em>Condensed Matter Field Theory</em>.
    </li>
    <li>
      <strong>Anderson</strong>,
      <em>Basic Notions of Condensed Matter Physics</em>.
    </li>
    <li>
      <strong>Blaizot</strong> e <strong>Ripka</strong>,
      <em>Quantum Theory of Finite Systems</em>.
    </li>
    <li>
      <strong>Negele</strong> e <strong>Orland</strong>,
      <em>Quantum Many-Particle Systems</em>.
    </li>
  </ul>
  <p>
    <strong>Notas de aula:</strong> Balents, Nayak, Tremblay, dentre outras.
  </p>

GITHUB_LINK: https://github.com/Academic-Codex/PFG5295-Teoria-de-Muitos-Corpos-e-Materia-Condensada

HERO_FILE: muitos-corpos-e-materia-condensada.png
